project:
  type: website

website:
  title: "Charlotte Curtis"
  site-url: https://www.charlottecurtis.ca/
  favicon: img/icon.svg
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: docs/curtis-cv.pdf
        text: CV  
  page-footer:
    center: "© Copyright 2026 Charlotte Curtis. Licensed [CC-BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)."
    right: Made with [![Quarto](https://quarto.org/quarto.png){height=1em}](https://quarto.org/)

page-layout: full
format:
  html:
    theme: [simplex, brand, assets/theme.scss]
    toc: false



